const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('cm', {
  setIgnore: (ig) => ipcRenderer.send('set-ignore', ig),
  grabFocus: () => ipcRenderer.send('grab-focus'),
  captureScreen: () => ipcRenderer.invoke('capture-screen'),
  getScreenSource: () => ipcRenderer.invoke('get-screen-source'),
  getDisplays: () => ipcRenderer.invoke('get-displays'),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  copyImage: (dataURL) => ipcRenderer.send('copy-image', dataURL),
  copyText: (text) => ipcRenderer.send('copy-text', text),
  shorten: (p) => ipcRenderer.invoke('shorten', p),
  translate: (p) => ipcRenderer.invoke('translate', p),
  verifyPro: (p) => ipcRenderer.invoke('verify-pro', p),
  aiChat: (p) => ipcRenderer.invoke('ai-chat', p),
  aiProxy: (p) => ipcRenderer.invoke('ai-proxy', p),
  sttProxy: (p) => ipcRenderer.invoke('stt-proxy', p),
  aiOcr: (p) => ipcRenderer.invoke('ai-ocr', p),
  meetingSubmit: (p) => ipcRenderer.invoke('meeting-submit', p),
  meetingStatus: (p) => ipcRenderer.invoke('meeting-status', p),
  saveImage: (p) => ipcRenderer.invoke('save-image', p),
  saveText: (p) => ipcRenderer.invoke('save-text', p),
  saveBinary: (p) => ipcRenderer.invoke('save-binary', p),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  saveTemplate: () => ipcRenderer.invoke('save-template'),
  quit: () => ipcRenderer.send('quit-app'),
  hideToTray: () => ipcRenderer.send('hide-to-tray'),
  pickRosterFile: () => ipcRenderer.invoke('pick-roster'),
  readPath: (p) => ipcRenderer.invoke('read-path', p),
  pickBackup: () => ipcRenderer.invoke('pick-backup'),
  suDelete: (o) => ipcRenderer.invoke('su-delete', o),
  suAdminList: (o) => ipcRenderer.invoke('su-admin-list', o),
  suAdminDelete: (o) => ipcRenderer.invoke('su-admin-delete', o),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  setShortcuts: (obj) => ipcRenderer.send('set-shortcuts', obj),
  onHotkey: (h) => ['hk-ring','hk-spot','hk-lens','hk-lens-rect','hk-spotlens','hk-zoom','hk-draw','hk-snip','hk-dock','hk-escape']
    .forEach(ch => ipcRenderer.on(ch, () => h(ch))),
  onBoundsChanged: (h) => ipcRenderer.on('bounds-changed', h),
});
